### ISSUE TITLE
Can not run the examples

### ISSUE THREAD

**Issue by hoanglethanhson** [sherpavel/Argon#1]
Hello, I've just cloned your project to my PC and opened it in IntelliJ.
I read your README and tried to run the example files like **Polygon.java** but the IDE run button didn't show up although I saw there was a main function in the class file. Can you help me to run it? Thanks in advance.
[](url
![Untitled](https://user-images.githubusercontent.com/31215388/134153833-cef8a972-6c06-4adb-86a7-094526f9967f.png)
)

**Comment by sherpavel** [comment]
Hi!
You first need setup the project's Java SDK (IntelliJ suggestion in the top right corner). It should work afterwards.
